package org.example.bdus1.domain.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.bdus1.domain.dao.po.CustomerAccountInfoPo;

public interface CustomerAccountInfoPoMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_account_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String accountNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_account_info
     *
     * @mbg.generated
     */
    int insert(CustomerAccountInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_account_info
     *
     * @mbg.generated
     */
    int insertSelective(CustomerAccountInfoPo record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_account_info
     *
     * @mbg.generated
     */
    CustomerAccountInfoPo selectByPrimaryKey(String accountNumber);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_account_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CustomerAccountInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_account_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CustomerAccountInfoPo record);
}