package org.example.bdus1.domain.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.bdus1.domain.dao.mdo.RmrgtRegInMdo;

public interface RmrgtRegInMdoMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_in
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String remittanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_in
     *
     * @mbg.generated
     */
    int insert(RmrgtRegInMdo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_in
     *
     * @mbg.generated
     */
    int insertSelective(RmrgtRegInMdo record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_in
     *
     * @mbg.generated
     */
    RmrgtRegInMdo selectByPrimaryKey(String remittanceId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_in
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RmrgtRegInMdo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_in
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RmrgtRegInMdo record);
}