package org.example.bdus1.domain.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.bdus1.domain.dao.mdo.RmrgtRegOutMdo;

public interface RmrgtRegOutMdoMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_out
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String remittanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_out
     *
     * @mbg.generated
     */
    int insert(RmrgtRegOutMdo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_out
     *
     * @mbg.generated
     */
    int insertSelective(RmrgtRegOutMdo record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_out
     *
     * @mbg.generated
     */
    RmrgtRegOutMdo selectByPrimaryKey(String remittanceId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_out
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RmrgtRegOutMdo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_out
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RmrgtRegOutMdo record);
}