package org.example.bdus1.domain.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.bdus1.domain.dao.po.RmrgtLifecyclePo;

public interface RmrgtLifecyclePoMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String remittanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    int insert(RmrgtLifecyclePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    int insertSelective(RmrgtLifecyclePo record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    RmrgtLifecyclePo selectByPrimaryKey(String remittanceId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RmrgtLifecyclePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RmrgtLifecyclePo record);
}