package org.example.bdus2.domain.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.bdus2.domain.dao.po.CustomerAccountInfoPo;
import org.example.bdus2.domain.dao.po.CustomerAccountInfoPoExample;

public interface CustomerAccountInfoPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_account_info
     *
     * @mbg.generated
     */
    long countByExample(CustomerAccountInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_account_info
     *
     * @mbg.generated
     */
    int deleteByExample(CustomerAccountInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_account_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String accountNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_account_info
     *
     * @mbg.generated
     */
    int insert(CustomerAccountInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_account_info
     *
     * @mbg.generated
     */
    int insertSelective(CustomerAccountInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_account_info
     *
     * @mbg.generated
     */
    List<CustomerAccountInfoPo> selectByExample(CustomerAccountInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_account_info
     *
     * @mbg.generated
     */
    CustomerAccountInfoPo selectByPrimaryKey(String accountNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_account_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CustomerAccountInfoPo record, @Param("example") CustomerAccountInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_account_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CustomerAccountInfoPo record, @Param("example") CustomerAccountInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_account_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CustomerAccountInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_account_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CustomerAccountInfoPo record);
}