package org.example.bdus2.domain.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.bdus2.domain.dao.po.RmrgtRegInPo;
import org.example.bdus2.domain.dao.po.RmrgtRegInPoExample;

public interface RmrgtRegInPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_in
     *
     * @mbg.generated
     */
    long countByExample(RmrgtRegInPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_in
     *
     * @mbg.generated
     */
    int deleteByExample(RmrgtRegInPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_in
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String remittanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_in
     *
     * @mbg.generated
     */
    int insert(RmrgtRegInPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_in
     *
     * @mbg.generated
     */
    int insertSelective(RmrgtRegInPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_in
     *
     * @mbg.generated
     */
    List<RmrgtRegInPo> selectByExample(RmrgtRegInPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_in
     *
     * @mbg.generated
     */
    RmrgtRegInPo selectByPrimaryKey(String remittanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_in
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RmrgtRegInPo record, @Param("example") RmrgtRegInPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_in
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RmrgtRegInPo record, @Param("example") RmrgtRegInPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_in
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RmrgtRegInPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_in
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RmrgtRegInPo record);
}