package org.example.bdus1.domain.dao.po;

import java.math.BigDecimal;
import java.util.Date;

public class RmrgtRegInPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_reg_in.remittance_id
     *
     * @mbg.generated
     */
    private String remittanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_reg_in.transaction_date
     *
     * @mbg.generated
     */
    private String transactionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_reg_in.customer_number
     *
     * @mbg.generated
     */
    private String customerNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_reg_in.debit_credit_code
     *
     * @mbg.generated
     */
    private String debitCreditCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_reg_in.sender_account
     *
     * @mbg.generated
     */
    private String senderAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_reg_in.sender_name
     *
     * @mbg.generated
     */
    private String senderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_reg_in.sender_phone
     *
     * @mbg.generated
     */
    private String senderPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_reg_in.sender_id
     *
     * @mbg.generated
     */
    private String senderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_reg_in.sender_address
     *
     * @mbg.generated
     */
    private String senderAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_reg_in.currency_code
     *
     * @mbg.generated
     */
    private String currencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_reg_in.remittance_amount
     *
     * @mbg.generated
     */
    private BigDecimal remittanceAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_reg_in.fee_amount
     *
     * @mbg.generated
     */
    private BigDecimal feeAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_reg_in.recipient_name
     *
     * @mbg.generated
     */
    private String recipientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_reg_in.recipient_account
     *
     * @mbg.generated
     */
    private String recipientAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_reg_in.recipient_phone
     *
     * @mbg.generated
     */
    private String recipientPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_reg_in.recipient_address
     *
     * @mbg.generated
     */
    private String recipientAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_reg_in.interbank_status_code
     *
     * @mbg.generated
     */
    private String interbankStatusCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_reg_in.remittance_note
     *
     * @mbg.generated
     */
    private String remittanceNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_reg_in.zone_val
     *
     * @mbg.generated
     */
    private String zoneVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_reg_in.optimistic_lock_version
     *
     * @mbg.generated
     */
    private Integer optimisticLockVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_reg_in.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_reg_in.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_reg_in.remittance_id
     *
     * @return the value of tb_rmrgt_reg_in.remittance_id
     *
     * @mbg.generated
     */
    public String getRemittanceId() {
        return remittanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_reg_in.remittance_id
     *
     * @param remittanceId the value for tb_rmrgt_reg_in.remittance_id
     *
     * @mbg.generated
     */
    public void setRemittanceId(String remittanceId) {
        this.remittanceId = remittanceId == null ? null : remittanceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_reg_in.transaction_date
     *
     * @return the value of tb_rmrgt_reg_in.transaction_date
     *
     * @mbg.generated
     */
    public String getTransactionDate() {
        return transactionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_reg_in.transaction_date
     *
     * @param transactionDate the value for tb_rmrgt_reg_in.transaction_date
     *
     * @mbg.generated
     */
    public void setTransactionDate(String transactionDate) {
        this.transactionDate = transactionDate == null ? null : transactionDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_reg_in.customer_number
     *
     * @return the value of tb_rmrgt_reg_in.customer_number
     *
     * @mbg.generated
     */
    public String getCustomerNumber() {
        return customerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_reg_in.customer_number
     *
     * @param customerNumber the value for tb_rmrgt_reg_in.customer_number
     *
     * @mbg.generated
     */
    public void setCustomerNumber(String customerNumber) {
        this.customerNumber = customerNumber == null ? null : customerNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_reg_in.debit_credit_code
     *
     * @return the value of tb_rmrgt_reg_in.debit_credit_code
     *
     * @mbg.generated
     */
    public String getDebitCreditCode() {
        return debitCreditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_reg_in.debit_credit_code
     *
     * @param debitCreditCode the value for tb_rmrgt_reg_in.debit_credit_code
     *
     * @mbg.generated
     */
    public void setDebitCreditCode(String debitCreditCode) {
        this.debitCreditCode = debitCreditCode == null ? null : debitCreditCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_reg_in.sender_account
     *
     * @return the value of tb_rmrgt_reg_in.sender_account
     *
     * @mbg.generated
     */
    public String getSenderAccount() {
        return senderAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_reg_in.sender_account
     *
     * @param senderAccount the value for tb_rmrgt_reg_in.sender_account
     *
     * @mbg.generated
     */
    public void setSenderAccount(String senderAccount) {
        this.senderAccount = senderAccount == null ? null : senderAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_reg_in.sender_name
     *
     * @return the value of tb_rmrgt_reg_in.sender_name
     *
     * @mbg.generated
     */
    public String getSenderName() {
        return senderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_reg_in.sender_name
     *
     * @param senderName the value for tb_rmrgt_reg_in.sender_name
     *
     * @mbg.generated
     */
    public void setSenderName(String senderName) {
        this.senderName = senderName == null ? null : senderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_reg_in.sender_phone
     *
     * @return the value of tb_rmrgt_reg_in.sender_phone
     *
     * @mbg.generated
     */
    public String getSenderPhone() {
        return senderPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_reg_in.sender_phone
     *
     * @param senderPhone the value for tb_rmrgt_reg_in.sender_phone
     *
     * @mbg.generated
     */
    public void setSenderPhone(String senderPhone) {
        this.senderPhone = senderPhone == null ? null : senderPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_reg_in.sender_id
     *
     * @return the value of tb_rmrgt_reg_in.sender_id
     *
     * @mbg.generated
     */
    public String getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_reg_in.sender_id
     *
     * @param senderId the value for tb_rmrgt_reg_in.sender_id
     *
     * @mbg.generated
     */
    public void setSenderId(String senderId) {
        this.senderId = senderId == null ? null : senderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_reg_in.sender_address
     *
     * @return the value of tb_rmrgt_reg_in.sender_address
     *
     * @mbg.generated
     */
    public String getSenderAddress() {
        return senderAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_reg_in.sender_address
     *
     * @param senderAddress the value for tb_rmrgt_reg_in.sender_address
     *
     * @mbg.generated
     */
    public void setSenderAddress(String senderAddress) {
        this.senderAddress = senderAddress == null ? null : senderAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_reg_in.currency_code
     *
     * @return the value of tb_rmrgt_reg_in.currency_code
     *
     * @mbg.generated
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_reg_in.currency_code
     *
     * @param currencyCode the value for tb_rmrgt_reg_in.currency_code
     *
     * @mbg.generated
     */
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode == null ? null : currencyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_reg_in.remittance_amount
     *
     * @return the value of tb_rmrgt_reg_in.remittance_amount
     *
     * @mbg.generated
     */
    public BigDecimal getRemittanceAmount() {
        return remittanceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_reg_in.remittance_amount
     *
     * @param remittanceAmount the value for tb_rmrgt_reg_in.remittance_amount
     *
     * @mbg.generated
     */
    public void setRemittanceAmount(BigDecimal remittanceAmount) {
        this.remittanceAmount = remittanceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_reg_in.fee_amount
     *
     * @return the value of tb_rmrgt_reg_in.fee_amount
     *
     * @mbg.generated
     */
    public BigDecimal getFeeAmount() {
        return feeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_reg_in.fee_amount
     *
     * @param feeAmount the value for tb_rmrgt_reg_in.fee_amount
     *
     * @mbg.generated
     */
    public void setFeeAmount(BigDecimal feeAmount) {
        this.feeAmount = feeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_reg_in.recipient_name
     *
     * @return the value of tb_rmrgt_reg_in.recipient_name
     *
     * @mbg.generated
     */
    public String getRecipientName() {
        return recipientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_reg_in.recipient_name
     *
     * @param recipientName the value for tb_rmrgt_reg_in.recipient_name
     *
     * @mbg.generated
     */
    public void setRecipientName(String recipientName) {
        this.recipientName = recipientName == null ? null : recipientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_reg_in.recipient_account
     *
     * @return the value of tb_rmrgt_reg_in.recipient_account
     *
     * @mbg.generated
     */
    public String getRecipientAccount() {
        return recipientAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_reg_in.recipient_account
     *
     * @param recipientAccount the value for tb_rmrgt_reg_in.recipient_account
     *
     * @mbg.generated
     */
    public void setRecipientAccount(String recipientAccount) {
        this.recipientAccount = recipientAccount == null ? null : recipientAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_reg_in.recipient_phone
     *
     * @return the value of tb_rmrgt_reg_in.recipient_phone
     *
     * @mbg.generated
     */
    public String getRecipientPhone() {
        return recipientPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_reg_in.recipient_phone
     *
     * @param recipientPhone the value for tb_rmrgt_reg_in.recipient_phone
     *
     * @mbg.generated
     */
    public void setRecipientPhone(String recipientPhone) {
        this.recipientPhone = recipientPhone == null ? null : recipientPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_reg_in.recipient_address
     *
     * @return the value of tb_rmrgt_reg_in.recipient_address
     *
     * @mbg.generated
     */
    public String getRecipientAddress() {
        return recipientAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_reg_in.recipient_address
     *
     * @param recipientAddress the value for tb_rmrgt_reg_in.recipient_address
     *
     * @mbg.generated
     */
    public void setRecipientAddress(String recipientAddress) {
        this.recipientAddress = recipientAddress == null ? null : recipientAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_reg_in.interbank_status_code
     *
     * @return the value of tb_rmrgt_reg_in.interbank_status_code
     *
     * @mbg.generated
     */
    public String getInterbankStatusCode() {
        return interbankStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_reg_in.interbank_status_code
     *
     * @param interbankStatusCode the value for tb_rmrgt_reg_in.interbank_status_code
     *
     * @mbg.generated
     */
    public void setInterbankStatusCode(String interbankStatusCode) {
        this.interbankStatusCode = interbankStatusCode == null ? null : interbankStatusCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_reg_in.remittance_note
     *
     * @return the value of tb_rmrgt_reg_in.remittance_note
     *
     * @mbg.generated
     */
    public String getRemittanceNote() {
        return remittanceNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_reg_in.remittance_note
     *
     * @param remittanceNote the value for tb_rmrgt_reg_in.remittance_note
     *
     * @mbg.generated
     */
    public void setRemittanceNote(String remittanceNote) {
        this.remittanceNote = remittanceNote == null ? null : remittanceNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_reg_in.zone_val
     *
     * @return the value of tb_rmrgt_reg_in.zone_val
     *
     * @mbg.generated
     */
    public String getZoneVal() {
        return zoneVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_reg_in.zone_val
     *
     * @param zoneVal the value for tb_rmrgt_reg_in.zone_val
     *
     * @mbg.generated
     */
    public void setZoneVal(String zoneVal) {
        this.zoneVal = zoneVal == null ? null : zoneVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_reg_in.optimistic_lock_version
     *
     * @return the value of tb_rmrgt_reg_in.optimistic_lock_version
     *
     * @mbg.generated
     */
    public Integer getOptimisticLockVersion() {
        return optimisticLockVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_reg_in.optimistic_lock_version
     *
     * @param optimisticLockVersion the value for tb_rmrgt_reg_in.optimistic_lock_version
     *
     * @mbg.generated
     */
    public void setOptimisticLockVersion(Integer optimisticLockVersion) {
        this.optimisticLockVersion = optimisticLockVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_reg_in.created_at
     *
     * @return the value of tb_rmrgt_reg_in.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_reg_in.created_at
     *
     * @param createdAt the value for tb_rmrgt_reg_in.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_reg_in.updated_at
     *
     * @return the value of tb_rmrgt_reg_in.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_reg_in.updated_at
     *
     * @param updatedAt the value for tb_rmrgt_reg_in.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}