package org.example.bdus1.domain.dao.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RmrgtLifecyclePoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    public RmrgtLifecyclePoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRemittanceIdIsNull() {
            addCriterion("remittance_id is null");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdIsNotNull() {
            addCriterion("remittance_id is not null");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdEqualTo(String value) {
            addCriterion("remittance_id =", value, "remittanceId");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdNotEqualTo(String value) {
            addCriterion("remittance_id <>", value, "remittanceId");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdGreaterThan(String value) {
            addCriterion("remittance_id >", value, "remittanceId");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdGreaterThanOrEqualTo(String value) {
            addCriterion("remittance_id >=", value, "remittanceId");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdLessThan(String value) {
            addCriterion("remittance_id <", value, "remittanceId");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdLessThanOrEqualTo(String value) {
            addCriterion("remittance_id <=", value, "remittanceId");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdLike(String value) {
            addCriterion("remittance_id like", value, "remittanceId");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdNotLike(String value) {
            addCriterion("remittance_id not like", value, "remittanceId");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdIn(List<String> values) {
            addCriterion("remittance_id in", values, "remittanceId");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdNotIn(List<String> values) {
            addCriterion("remittance_id not in", values, "remittanceId");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdBetween(String value1, String value2) {
            addCriterion("remittance_id between", value1, value2, "remittanceId");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdNotBetween(String value1, String value2) {
            addCriterion("remittance_id not between", value1, value2, "remittanceId");
            return (Criteria) this;
        }

        public Criteria andTransactionDateIsNull() {
            addCriterion("transaction_date is null");
            return (Criteria) this;
        }

        public Criteria andTransactionDateIsNotNull() {
            addCriterion("transaction_date is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionDateEqualTo(String value) {
            addCriterion("transaction_date =", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateNotEqualTo(String value) {
            addCriterion("transaction_date <>", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateGreaterThan(String value) {
            addCriterion("transaction_date >", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateGreaterThanOrEqualTo(String value) {
            addCriterion("transaction_date >=", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateLessThan(String value) {
            addCriterion("transaction_date <", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateLessThanOrEqualTo(String value) {
            addCriterion("transaction_date <=", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateLike(String value) {
            addCriterion("transaction_date like", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateNotLike(String value) {
            addCriterion("transaction_date not like", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateIn(List<String> values) {
            addCriterion("transaction_date in", values, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateNotIn(List<String> values) {
            addCriterion("transaction_date not in", values, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateBetween(String value1, String value2) {
            addCriterion("transaction_date between", value1, value2, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateNotBetween(String value1, String value2) {
            addCriterion("transaction_date not between", value1, value2, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andStatusChangeDateIsNull() {
            addCriterion("status_change_date is null");
            return (Criteria) this;
        }

        public Criteria andStatusChangeDateIsNotNull() {
            addCriterion("status_change_date is not null");
            return (Criteria) this;
        }

        public Criteria andStatusChangeDateEqualTo(String value) {
            addCriterion("status_change_date =", value, "statusChangeDate");
            return (Criteria) this;
        }

        public Criteria andStatusChangeDateNotEqualTo(String value) {
            addCriterion("status_change_date <>", value, "statusChangeDate");
            return (Criteria) this;
        }

        public Criteria andStatusChangeDateGreaterThan(String value) {
            addCriterion("status_change_date >", value, "statusChangeDate");
            return (Criteria) this;
        }

        public Criteria andStatusChangeDateGreaterThanOrEqualTo(String value) {
            addCriterion("status_change_date >=", value, "statusChangeDate");
            return (Criteria) this;
        }

        public Criteria andStatusChangeDateLessThan(String value) {
            addCriterion("status_change_date <", value, "statusChangeDate");
            return (Criteria) this;
        }

        public Criteria andStatusChangeDateLessThanOrEqualTo(String value) {
            addCriterion("status_change_date <=", value, "statusChangeDate");
            return (Criteria) this;
        }

        public Criteria andStatusChangeDateLike(String value) {
            addCriterion("status_change_date like", value, "statusChangeDate");
            return (Criteria) this;
        }

        public Criteria andStatusChangeDateNotLike(String value) {
            addCriterion("status_change_date not like", value, "statusChangeDate");
            return (Criteria) this;
        }

        public Criteria andStatusChangeDateIn(List<String> values) {
            addCriterion("status_change_date in", values, "statusChangeDate");
            return (Criteria) this;
        }

        public Criteria andStatusChangeDateNotIn(List<String> values) {
            addCriterion("status_change_date not in", values, "statusChangeDate");
            return (Criteria) this;
        }

        public Criteria andStatusChangeDateBetween(String value1, String value2) {
            addCriterion("status_change_date between", value1, value2, "statusChangeDate");
            return (Criteria) this;
        }

        public Criteria andStatusChangeDateNotBetween(String value1, String value2) {
            addCriterion("status_change_date not between", value1, value2, "statusChangeDate");
            return (Criteria) this;
        }

        public Criteria andDirectionCodeIsNull() {
            addCriterion("direction_code is null");
            return (Criteria) this;
        }

        public Criteria andDirectionCodeIsNotNull() {
            addCriterion("direction_code is not null");
            return (Criteria) this;
        }

        public Criteria andDirectionCodeEqualTo(String value) {
            addCriterion("direction_code =", value, "directionCode");
            return (Criteria) this;
        }

        public Criteria andDirectionCodeNotEqualTo(String value) {
            addCriterion("direction_code <>", value, "directionCode");
            return (Criteria) this;
        }

        public Criteria andDirectionCodeGreaterThan(String value) {
            addCriterion("direction_code >", value, "directionCode");
            return (Criteria) this;
        }

        public Criteria andDirectionCodeGreaterThanOrEqualTo(String value) {
            addCriterion("direction_code >=", value, "directionCode");
            return (Criteria) this;
        }

        public Criteria andDirectionCodeLessThan(String value) {
            addCriterion("direction_code <", value, "directionCode");
            return (Criteria) this;
        }

        public Criteria andDirectionCodeLessThanOrEqualTo(String value) {
            addCriterion("direction_code <=", value, "directionCode");
            return (Criteria) this;
        }

        public Criteria andDirectionCodeLike(String value) {
            addCriterion("direction_code like", value, "directionCode");
            return (Criteria) this;
        }

        public Criteria andDirectionCodeNotLike(String value) {
            addCriterion("direction_code not like", value, "directionCode");
            return (Criteria) this;
        }

        public Criteria andDirectionCodeIn(List<String> values) {
            addCriterion("direction_code in", values, "directionCode");
            return (Criteria) this;
        }

        public Criteria andDirectionCodeNotIn(List<String> values) {
            addCriterion("direction_code not in", values, "directionCode");
            return (Criteria) this;
        }

        public Criteria andDirectionCodeBetween(String value1, String value2) {
            addCriterion("direction_code between", value1, value2, "directionCode");
            return (Criteria) this;
        }

        public Criteria andDirectionCodeNotBetween(String value1, String value2) {
            addCriterion("direction_code not between", value1, value2, "directionCode");
            return (Criteria) this;
        }

        public Criteria andStatusChangeReasonIsNull() {
            addCriterion("status_change_reason is null");
            return (Criteria) this;
        }

        public Criteria andStatusChangeReasonIsNotNull() {
            addCriterion("status_change_reason is not null");
            return (Criteria) this;
        }

        public Criteria andStatusChangeReasonEqualTo(String value) {
            addCriterion("status_change_reason =", value, "statusChangeReason");
            return (Criteria) this;
        }

        public Criteria andStatusChangeReasonNotEqualTo(String value) {
            addCriterion("status_change_reason <>", value, "statusChangeReason");
            return (Criteria) this;
        }

        public Criteria andStatusChangeReasonGreaterThan(String value) {
            addCriterion("status_change_reason >", value, "statusChangeReason");
            return (Criteria) this;
        }

        public Criteria andStatusChangeReasonGreaterThanOrEqualTo(String value) {
            addCriterion("status_change_reason >=", value, "statusChangeReason");
            return (Criteria) this;
        }

        public Criteria andStatusChangeReasonLessThan(String value) {
            addCriterion("status_change_reason <", value, "statusChangeReason");
            return (Criteria) this;
        }

        public Criteria andStatusChangeReasonLessThanOrEqualTo(String value) {
            addCriterion("status_change_reason <=", value, "statusChangeReason");
            return (Criteria) this;
        }

        public Criteria andStatusChangeReasonLike(String value) {
            addCriterion("status_change_reason like", value, "statusChangeReason");
            return (Criteria) this;
        }

        public Criteria andStatusChangeReasonNotLike(String value) {
            addCriterion("status_change_reason not like", value, "statusChangeReason");
            return (Criteria) this;
        }

        public Criteria andStatusChangeReasonIn(List<String> values) {
            addCriterion("status_change_reason in", values, "statusChangeReason");
            return (Criteria) this;
        }

        public Criteria andStatusChangeReasonNotIn(List<String> values) {
            addCriterion("status_change_reason not in", values, "statusChangeReason");
            return (Criteria) this;
        }

        public Criteria andStatusChangeReasonBetween(String value1, String value2) {
            addCriterion("status_change_reason between", value1, value2, "statusChangeReason");
            return (Criteria) this;
        }

        public Criteria andStatusChangeReasonNotBetween(String value1, String value2) {
            addCriterion("status_change_reason not between", value1, value2, "statusChangeReason");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeIsNull() {
            addCriterion("currency_code is null");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeIsNotNull() {
            addCriterion("currency_code is not null");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeEqualTo(String value) {
            addCriterion("currency_code =", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeNotEqualTo(String value) {
            addCriterion("currency_code <>", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeGreaterThan(String value) {
            addCriterion("currency_code >", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeGreaterThanOrEqualTo(String value) {
            addCriterion("currency_code >=", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeLessThan(String value) {
            addCriterion("currency_code <", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeLessThanOrEqualTo(String value) {
            addCriterion("currency_code <=", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeLike(String value) {
            addCriterion("currency_code like", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeNotLike(String value) {
            addCriterion("currency_code not like", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeIn(List<String> values) {
            addCriterion("currency_code in", values, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeNotIn(List<String> values) {
            addCriterion("currency_code not in", values, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeBetween(String value1, String value2) {
            addCriterion("currency_code between", value1, value2, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeNotBetween(String value1, String value2) {
            addCriterion("currency_code not between", value1, value2, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andGlobalTrackingNumberIsNull() {
            addCriterion("global_tracking_number is null");
            return (Criteria) this;
        }

        public Criteria andGlobalTrackingNumberIsNotNull() {
            addCriterion("global_tracking_number is not null");
            return (Criteria) this;
        }

        public Criteria andGlobalTrackingNumberEqualTo(String value) {
            addCriterion("global_tracking_number =", value, "globalTrackingNumber");
            return (Criteria) this;
        }

        public Criteria andGlobalTrackingNumberNotEqualTo(String value) {
            addCriterion("global_tracking_number <>", value, "globalTrackingNumber");
            return (Criteria) this;
        }

        public Criteria andGlobalTrackingNumberGreaterThan(String value) {
            addCriterion("global_tracking_number >", value, "globalTrackingNumber");
            return (Criteria) this;
        }

        public Criteria andGlobalTrackingNumberGreaterThanOrEqualTo(String value) {
            addCriterion("global_tracking_number >=", value, "globalTrackingNumber");
            return (Criteria) this;
        }

        public Criteria andGlobalTrackingNumberLessThan(String value) {
            addCriterion("global_tracking_number <", value, "globalTrackingNumber");
            return (Criteria) this;
        }

        public Criteria andGlobalTrackingNumberLessThanOrEqualTo(String value) {
            addCriterion("global_tracking_number <=", value, "globalTrackingNumber");
            return (Criteria) this;
        }

        public Criteria andGlobalTrackingNumberLike(String value) {
            addCriterion("global_tracking_number like", value, "globalTrackingNumber");
            return (Criteria) this;
        }

        public Criteria andGlobalTrackingNumberNotLike(String value) {
            addCriterion("global_tracking_number not like", value, "globalTrackingNumber");
            return (Criteria) this;
        }

        public Criteria andGlobalTrackingNumberIn(List<String> values) {
            addCriterion("global_tracking_number in", values, "globalTrackingNumber");
            return (Criteria) this;
        }

        public Criteria andGlobalTrackingNumberNotIn(List<String> values) {
            addCriterion("global_tracking_number not in", values, "globalTrackingNumber");
            return (Criteria) this;
        }

        public Criteria andGlobalTrackingNumberBetween(String value1, String value2) {
            addCriterion("global_tracking_number between", value1, value2, "globalTrackingNumber");
            return (Criteria) this;
        }

        public Criteria andGlobalTrackingNumberNotBetween(String value1, String value2) {
            addCriterion("global_tracking_number not between", value1, value2, "globalTrackingNumber");
            return (Criteria) this;
        }

        public Criteria andZoneValIsNull() {
            addCriterion("zone_val is null");
            return (Criteria) this;
        }

        public Criteria andZoneValIsNotNull() {
            addCriterion("zone_val is not null");
            return (Criteria) this;
        }

        public Criteria andZoneValEqualTo(String value) {
            addCriterion("zone_val =", value, "zoneVal");
            return (Criteria) this;
        }

        public Criteria andZoneValNotEqualTo(String value) {
            addCriterion("zone_val <>", value, "zoneVal");
            return (Criteria) this;
        }

        public Criteria andZoneValGreaterThan(String value) {
            addCriterion("zone_val >", value, "zoneVal");
            return (Criteria) this;
        }

        public Criteria andZoneValGreaterThanOrEqualTo(String value) {
            addCriterion("zone_val >=", value, "zoneVal");
            return (Criteria) this;
        }

        public Criteria andZoneValLessThan(String value) {
            addCriterion("zone_val <", value, "zoneVal");
            return (Criteria) this;
        }

        public Criteria andZoneValLessThanOrEqualTo(String value) {
            addCriterion("zone_val <=", value, "zoneVal");
            return (Criteria) this;
        }

        public Criteria andZoneValLike(String value) {
            addCriterion("zone_val like", value, "zoneVal");
            return (Criteria) this;
        }

        public Criteria andZoneValNotLike(String value) {
            addCriterion("zone_val not like", value, "zoneVal");
            return (Criteria) this;
        }

        public Criteria andZoneValIn(List<String> values) {
            addCriterion("zone_val in", values, "zoneVal");
            return (Criteria) this;
        }

        public Criteria andZoneValNotIn(List<String> values) {
            addCriterion("zone_val not in", values, "zoneVal");
            return (Criteria) this;
        }

        public Criteria andZoneValBetween(String value1, String value2) {
            addCriterion("zone_val between", value1, value2, "zoneVal");
            return (Criteria) this;
        }

        public Criteria andZoneValNotBetween(String value1, String value2) {
            addCriterion("zone_val not between", value1, value2, "zoneVal");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}