package org.example.common.domain.dao.mdo;

import java.util.Date;

public class CustomerInfoMdo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer_info.customer_number
     *
     * @mbg.generated
     */
    private String customerNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer_info.customer_name
     *
     * @mbg.generated
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer_info.customer_phone
     *
     * @mbg.generated
     */
    private String customerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer_info.customer_id
     *
     * @mbg.generated
     */
    private String customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer_info.customer_email
     *
     * @mbg.generated
     */
    private String customerEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer_info.customer_address
     *
     * @mbg.generated
     */
    private String customerAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer_info.customer_occupation
     *
     * @mbg.generated
     */
    private String customerOccupation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer_info.customer_status
     *
     * @mbg.generated
     */
    private String customerStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer_info.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer_info.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer_info.customer_number
     *
     * @return the value of tb_customer_info.customer_number
     *
     * @mbg.generated
     */
    public String getCustomerNumber() {
        return customerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer_info.customer_number
     *
     * @param customerNumber the value for tb_customer_info.customer_number
     *
     * @mbg.generated
     */
    public void setCustomerNumber(String customerNumber) {
        this.customerNumber = customerNumber == null ? null : customerNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer_info.customer_name
     *
     * @return the value of tb_customer_info.customer_name
     *
     * @mbg.generated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer_info.customer_name
     *
     * @param customerName the value for tb_customer_info.customer_name
     *
     * @mbg.generated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer_info.customer_phone
     *
     * @return the value of tb_customer_info.customer_phone
     *
     * @mbg.generated
     */
    public String getCustomerPhone() {
        return customerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer_info.customer_phone
     *
     * @param customerPhone the value for tb_customer_info.customer_phone
     *
     * @mbg.generated
     */
    public void setCustomerPhone(String customerPhone) {
        this.customerPhone = customerPhone == null ? null : customerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer_info.customer_id
     *
     * @return the value of tb_customer_info.customer_id
     *
     * @mbg.generated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer_info.customer_id
     *
     * @param customerId the value for tb_customer_info.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer_info.customer_email
     *
     * @return the value of tb_customer_info.customer_email
     *
     * @mbg.generated
     */
    public String getCustomerEmail() {
        return customerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer_info.customer_email
     *
     * @param customerEmail the value for tb_customer_info.customer_email
     *
     * @mbg.generated
     */
    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail == null ? null : customerEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer_info.customer_address
     *
     * @return the value of tb_customer_info.customer_address
     *
     * @mbg.generated
     */
    public String getCustomerAddress() {
        return customerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer_info.customer_address
     *
     * @param customerAddress the value for tb_customer_info.customer_address
     *
     * @mbg.generated
     */
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress == null ? null : customerAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer_info.customer_occupation
     *
     * @return the value of tb_customer_info.customer_occupation
     *
     * @mbg.generated
     */
    public String getCustomerOccupation() {
        return customerOccupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer_info.customer_occupation
     *
     * @param customerOccupation the value for tb_customer_info.customer_occupation
     *
     * @mbg.generated
     */
    public void setCustomerOccupation(String customerOccupation) {
        this.customerOccupation = customerOccupation == null ? null : customerOccupation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer_info.customer_status
     *
     * @return the value of tb_customer_info.customer_status
     *
     * @mbg.generated
     */
    public String getCustomerStatus() {
        return customerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer_info.customer_status
     *
     * @param customerStatus the value for tb_customer_info.customer_status
     *
     * @mbg.generated
     */
    public void setCustomerStatus(String customerStatus) {
        this.customerStatus = customerStatus == null ? null : customerStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer_info.created_at
     *
     * @return the value of tb_customer_info.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer_info.created_at
     *
     * @param createdAt the value for tb_customer_info.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer_info.updated_at
     *
     * @return the value of tb_customer_info.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer_info.updated_at
     *
     * @param updatedAt the value for tb_customer_info.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}