package com.example.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.common.domain.dao.po.CustomerInfoPo;
import org.example.common.domain.dao.po.CustomerInfoPoExample;

public interface CustomerInfoPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_info
     *
     * @mbg.generated
     */
    long countByExample(CustomerInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_info
     *
     * @mbg.generated
     */
    int deleteByExample(CustomerInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String customerNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_info
     *
     * @mbg.generated
     */
    int insert(CustomerInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_info
     *
     * @mbg.generated
     */
    int insertSelective(CustomerInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_info
     *
     * @mbg.generated
     */
    List<CustomerInfoPo> selectByExample(CustomerInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_info
     *
     * @mbg.generated
     */
    CustomerInfoPo selectByPrimaryKey(String customerNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CustomerInfoPo record, @Param("example") CustomerInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CustomerInfoPo record, @Param("example") CustomerInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CustomerInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CustomerInfoPo record);
}