package org.example.bdus2.domain.dao.po;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RmrgtRegOutPoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_rmrgt_reg_out
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_rmrgt_reg_out
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_rmrgt_reg_out
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_out
     *
     * @mbg.generated
     */
    public RmrgtRegOutPoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_out
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_out
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_out
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_out
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_out
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_out
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_out
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_out
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_out
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_out
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_rmrgt_reg_out
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRemittanceIdIsNull() {
            addCriterion("remittance_id is null");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdIsNotNull() {
            addCriterion("remittance_id is not null");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdEqualTo(String value) {
            addCriterion("remittance_id =", value, "remittanceId");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdNotEqualTo(String value) {
            addCriterion("remittance_id <>", value, "remittanceId");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdGreaterThan(String value) {
            addCriterion("remittance_id >", value, "remittanceId");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdGreaterThanOrEqualTo(String value) {
            addCriterion("remittance_id >=", value, "remittanceId");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdLessThan(String value) {
            addCriterion("remittance_id <", value, "remittanceId");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdLessThanOrEqualTo(String value) {
            addCriterion("remittance_id <=", value, "remittanceId");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdLike(String value) {
            addCriterion("remittance_id like", value, "remittanceId");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdNotLike(String value) {
            addCriterion("remittance_id not like", value, "remittanceId");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdIn(List<String> values) {
            addCriterion("remittance_id in", values, "remittanceId");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdNotIn(List<String> values) {
            addCriterion("remittance_id not in", values, "remittanceId");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdBetween(String value1, String value2) {
            addCriterion("remittance_id between", value1, value2, "remittanceId");
            return (Criteria) this;
        }

        public Criteria andRemittanceIdNotBetween(String value1, String value2) {
            addCriterion("remittance_id not between", value1, value2, "remittanceId");
            return (Criteria) this;
        }

        public Criteria andTransactionDateIsNull() {
            addCriterion("transaction_date is null");
            return (Criteria) this;
        }

        public Criteria andTransactionDateIsNotNull() {
            addCriterion("transaction_date is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionDateEqualTo(String value) {
            addCriterion("transaction_date =", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateNotEqualTo(String value) {
            addCriterion("transaction_date <>", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateGreaterThan(String value) {
            addCriterion("transaction_date >", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateGreaterThanOrEqualTo(String value) {
            addCriterion("transaction_date >=", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateLessThan(String value) {
            addCriterion("transaction_date <", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateLessThanOrEqualTo(String value) {
            addCriterion("transaction_date <=", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateLike(String value) {
            addCriterion("transaction_date like", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateNotLike(String value) {
            addCriterion("transaction_date not like", value, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateIn(List<String> values) {
            addCriterion("transaction_date in", values, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateNotIn(List<String> values) {
            addCriterion("transaction_date not in", values, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateBetween(String value1, String value2) {
            addCriterion("transaction_date between", value1, value2, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andTransactionDateNotBetween(String value1, String value2) {
            addCriterion("transaction_date not between", value1, value2, "transactionDate");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberIsNull() {
            addCriterion("customer_number is null");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberIsNotNull() {
            addCriterion("customer_number is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberEqualTo(String value) {
            addCriterion("customer_number =", value, "customerNumber");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberNotEqualTo(String value) {
            addCriterion("customer_number <>", value, "customerNumber");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberGreaterThan(String value) {
            addCriterion("customer_number >", value, "customerNumber");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberGreaterThanOrEqualTo(String value) {
            addCriterion("customer_number >=", value, "customerNumber");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberLessThan(String value) {
            addCriterion("customer_number <", value, "customerNumber");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberLessThanOrEqualTo(String value) {
            addCriterion("customer_number <=", value, "customerNumber");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberLike(String value) {
            addCriterion("customer_number like", value, "customerNumber");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberNotLike(String value) {
            addCriterion("customer_number not like", value, "customerNumber");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberIn(List<String> values) {
            addCriterion("customer_number in", values, "customerNumber");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberNotIn(List<String> values) {
            addCriterion("customer_number not in", values, "customerNumber");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberBetween(String value1, String value2) {
            addCriterion("customer_number between", value1, value2, "customerNumber");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberNotBetween(String value1, String value2) {
            addCriterion("customer_number not between", value1, value2, "customerNumber");
            return (Criteria) this;
        }

        public Criteria andDebitCreditCodeIsNull() {
            addCriterion("debit_credit_code is null");
            return (Criteria) this;
        }

        public Criteria andDebitCreditCodeIsNotNull() {
            addCriterion("debit_credit_code is not null");
            return (Criteria) this;
        }

        public Criteria andDebitCreditCodeEqualTo(String value) {
            addCriterion("debit_credit_code =", value, "debitCreditCode");
            return (Criteria) this;
        }

        public Criteria andDebitCreditCodeNotEqualTo(String value) {
            addCriterion("debit_credit_code <>", value, "debitCreditCode");
            return (Criteria) this;
        }

        public Criteria andDebitCreditCodeGreaterThan(String value) {
            addCriterion("debit_credit_code >", value, "debitCreditCode");
            return (Criteria) this;
        }

        public Criteria andDebitCreditCodeGreaterThanOrEqualTo(String value) {
            addCriterion("debit_credit_code >=", value, "debitCreditCode");
            return (Criteria) this;
        }

        public Criteria andDebitCreditCodeLessThan(String value) {
            addCriterion("debit_credit_code <", value, "debitCreditCode");
            return (Criteria) this;
        }

        public Criteria andDebitCreditCodeLessThanOrEqualTo(String value) {
            addCriterion("debit_credit_code <=", value, "debitCreditCode");
            return (Criteria) this;
        }

        public Criteria andDebitCreditCodeLike(String value) {
            addCriterion("debit_credit_code like", value, "debitCreditCode");
            return (Criteria) this;
        }

        public Criteria andDebitCreditCodeNotLike(String value) {
            addCriterion("debit_credit_code not like", value, "debitCreditCode");
            return (Criteria) this;
        }

        public Criteria andDebitCreditCodeIn(List<String> values) {
            addCriterion("debit_credit_code in", values, "debitCreditCode");
            return (Criteria) this;
        }

        public Criteria andDebitCreditCodeNotIn(List<String> values) {
            addCriterion("debit_credit_code not in", values, "debitCreditCode");
            return (Criteria) this;
        }

        public Criteria andDebitCreditCodeBetween(String value1, String value2) {
            addCriterion("debit_credit_code between", value1, value2, "debitCreditCode");
            return (Criteria) this;
        }

        public Criteria andDebitCreditCodeNotBetween(String value1, String value2) {
            addCriterion("debit_credit_code not between", value1, value2, "debitCreditCode");
            return (Criteria) this;
        }

        public Criteria andSenderAccountIsNull() {
            addCriterion("sender_account is null");
            return (Criteria) this;
        }

        public Criteria andSenderAccountIsNotNull() {
            addCriterion("sender_account is not null");
            return (Criteria) this;
        }

        public Criteria andSenderAccountEqualTo(String value) {
            addCriterion("sender_account =", value, "senderAccount");
            return (Criteria) this;
        }

        public Criteria andSenderAccountNotEqualTo(String value) {
            addCriterion("sender_account <>", value, "senderAccount");
            return (Criteria) this;
        }

        public Criteria andSenderAccountGreaterThan(String value) {
            addCriterion("sender_account >", value, "senderAccount");
            return (Criteria) this;
        }

        public Criteria andSenderAccountGreaterThanOrEqualTo(String value) {
            addCriterion("sender_account >=", value, "senderAccount");
            return (Criteria) this;
        }

        public Criteria andSenderAccountLessThan(String value) {
            addCriterion("sender_account <", value, "senderAccount");
            return (Criteria) this;
        }

        public Criteria andSenderAccountLessThanOrEqualTo(String value) {
            addCriterion("sender_account <=", value, "senderAccount");
            return (Criteria) this;
        }

        public Criteria andSenderAccountLike(String value) {
            addCriterion("sender_account like", value, "senderAccount");
            return (Criteria) this;
        }

        public Criteria andSenderAccountNotLike(String value) {
            addCriterion("sender_account not like", value, "senderAccount");
            return (Criteria) this;
        }

        public Criteria andSenderAccountIn(List<String> values) {
            addCriterion("sender_account in", values, "senderAccount");
            return (Criteria) this;
        }

        public Criteria andSenderAccountNotIn(List<String> values) {
            addCriterion("sender_account not in", values, "senderAccount");
            return (Criteria) this;
        }

        public Criteria andSenderAccountBetween(String value1, String value2) {
            addCriterion("sender_account between", value1, value2, "senderAccount");
            return (Criteria) this;
        }

        public Criteria andSenderAccountNotBetween(String value1, String value2) {
            addCriterion("sender_account not between", value1, value2, "senderAccount");
            return (Criteria) this;
        }

        public Criteria andSenderNameIsNull() {
            addCriterion("sender_name is null");
            return (Criteria) this;
        }

        public Criteria andSenderNameIsNotNull() {
            addCriterion("sender_name is not null");
            return (Criteria) this;
        }

        public Criteria andSenderNameEqualTo(String value) {
            addCriterion("sender_name =", value, "senderName");
            return (Criteria) this;
        }

        public Criteria andSenderNameNotEqualTo(String value) {
            addCriterion("sender_name <>", value, "senderName");
            return (Criteria) this;
        }

        public Criteria andSenderNameGreaterThan(String value) {
            addCriterion("sender_name >", value, "senderName");
            return (Criteria) this;
        }

        public Criteria andSenderNameGreaterThanOrEqualTo(String value) {
            addCriterion("sender_name >=", value, "senderName");
            return (Criteria) this;
        }

        public Criteria andSenderNameLessThan(String value) {
            addCriterion("sender_name <", value, "senderName");
            return (Criteria) this;
        }

        public Criteria andSenderNameLessThanOrEqualTo(String value) {
            addCriterion("sender_name <=", value, "senderName");
            return (Criteria) this;
        }

        public Criteria andSenderNameLike(String value) {
            addCriterion("sender_name like", value, "senderName");
            return (Criteria) this;
        }

        public Criteria andSenderNameNotLike(String value) {
            addCriterion("sender_name not like", value, "senderName");
            return (Criteria) this;
        }

        public Criteria andSenderNameIn(List<String> values) {
            addCriterion("sender_name in", values, "senderName");
            return (Criteria) this;
        }

        public Criteria andSenderNameNotIn(List<String> values) {
            addCriterion("sender_name not in", values, "senderName");
            return (Criteria) this;
        }

        public Criteria andSenderNameBetween(String value1, String value2) {
            addCriterion("sender_name between", value1, value2, "senderName");
            return (Criteria) this;
        }

        public Criteria andSenderNameNotBetween(String value1, String value2) {
            addCriterion("sender_name not between", value1, value2, "senderName");
            return (Criteria) this;
        }

        public Criteria andSenderPhoneIsNull() {
            addCriterion("sender_phone is null");
            return (Criteria) this;
        }

        public Criteria andSenderPhoneIsNotNull() {
            addCriterion("sender_phone is not null");
            return (Criteria) this;
        }

        public Criteria andSenderPhoneEqualTo(String value) {
            addCriterion("sender_phone =", value, "senderPhone");
            return (Criteria) this;
        }

        public Criteria andSenderPhoneNotEqualTo(String value) {
            addCriterion("sender_phone <>", value, "senderPhone");
            return (Criteria) this;
        }

        public Criteria andSenderPhoneGreaterThan(String value) {
            addCriterion("sender_phone >", value, "senderPhone");
            return (Criteria) this;
        }

        public Criteria andSenderPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("sender_phone >=", value, "senderPhone");
            return (Criteria) this;
        }

        public Criteria andSenderPhoneLessThan(String value) {
            addCriterion("sender_phone <", value, "senderPhone");
            return (Criteria) this;
        }

        public Criteria andSenderPhoneLessThanOrEqualTo(String value) {
            addCriterion("sender_phone <=", value, "senderPhone");
            return (Criteria) this;
        }

        public Criteria andSenderPhoneLike(String value) {
            addCriterion("sender_phone like", value, "senderPhone");
            return (Criteria) this;
        }

        public Criteria andSenderPhoneNotLike(String value) {
            addCriterion("sender_phone not like", value, "senderPhone");
            return (Criteria) this;
        }

        public Criteria andSenderPhoneIn(List<String> values) {
            addCriterion("sender_phone in", values, "senderPhone");
            return (Criteria) this;
        }

        public Criteria andSenderPhoneNotIn(List<String> values) {
            addCriterion("sender_phone not in", values, "senderPhone");
            return (Criteria) this;
        }

        public Criteria andSenderPhoneBetween(String value1, String value2) {
            addCriterion("sender_phone between", value1, value2, "senderPhone");
            return (Criteria) this;
        }

        public Criteria andSenderPhoneNotBetween(String value1, String value2) {
            addCriterion("sender_phone not between", value1, value2, "senderPhone");
            return (Criteria) this;
        }

        public Criteria andSenderIdIsNull() {
            addCriterion("sender_id is null");
            return (Criteria) this;
        }

        public Criteria andSenderIdIsNotNull() {
            addCriterion("sender_id is not null");
            return (Criteria) this;
        }

        public Criteria andSenderIdEqualTo(String value) {
            addCriterion("sender_id =", value, "senderId");
            return (Criteria) this;
        }

        public Criteria andSenderIdNotEqualTo(String value) {
            addCriterion("sender_id <>", value, "senderId");
            return (Criteria) this;
        }

        public Criteria andSenderIdGreaterThan(String value) {
            addCriterion("sender_id >", value, "senderId");
            return (Criteria) this;
        }

        public Criteria andSenderIdGreaterThanOrEqualTo(String value) {
            addCriterion("sender_id >=", value, "senderId");
            return (Criteria) this;
        }

        public Criteria andSenderIdLessThan(String value) {
            addCriterion("sender_id <", value, "senderId");
            return (Criteria) this;
        }

        public Criteria andSenderIdLessThanOrEqualTo(String value) {
            addCriterion("sender_id <=", value, "senderId");
            return (Criteria) this;
        }

        public Criteria andSenderIdLike(String value) {
            addCriterion("sender_id like", value, "senderId");
            return (Criteria) this;
        }

        public Criteria andSenderIdNotLike(String value) {
            addCriterion("sender_id not like", value, "senderId");
            return (Criteria) this;
        }

        public Criteria andSenderIdIn(List<String> values) {
            addCriterion("sender_id in", values, "senderId");
            return (Criteria) this;
        }

        public Criteria andSenderIdNotIn(List<String> values) {
            addCriterion("sender_id not in", values, "senderId");
            return (Criteria) this;
        }

        public Criteria andSenderIdBetween(String value1, String value2) {
            addCriterion("sender_id between", value1, value2, "senderId");
            return (Criteria) this;
        }

        public Criteria andSenderIdNotBetween(String value1, String value2) {
            addCriterion("sender_id not between", value1, value2, "senderId");
            return (Criteria) this;
        }

        public Criteria andSenderAddressIsNull() {
            addCriterion("sender_address is null");
            return (Criteria) this;
        }

        public Criteria andSenderAddressIsNotNull() {
            addCriterion("sender_address is not null");
            return (Criteria) this;
        }

        public Criteria andSenderAddressEqualTo(String value) {
            addCriterion("sender_address =", value, "senderAddress");
            return (Criteria) this;
        }

        public Criteria andSenderAddressNotEqualTo(String value) {
            addCriterion("sender_address <>", value, "senderAddress");
            return (Criteria) this;
        }

        public Criteria andSenderAddressGreaterThan(String value) {
            addCriterion("sender_address >", value, "senderAddress");
            return (Criteria) this;
        }

        public Criteria andSenderAddressGreaterThanOrEqualTo(String value) {
            addCriterion("sender_address >=", value, "senderAddress");
            return (Criteria) this;
        }

        public Criteria andSenderAddressLessThan(String value) {
            addCriterion("sender_address <", value, "senderAddress");
            return (Criteria) this;
        }

        public Criteria andSenderAddressLessThanOrEqualTo(String value) {
            addCriterion("sender_address <=", value, "senderAddress");
            return (Criteria) this;
        }

        public Criteria andSenderAddressLike(String value) {
            addCriterion("sender_address like", value, "senderAddress");
            return (Criteria) this;
        }

        public Criteria andSenderAddressNotLike(String value) {
            addCriterion("sender_address not like", value, "senderAddress");
            return (Criteria) this;
        }

        public Criteria andSenderAddressIn(List<String> values) {
            addCriterion("sender_address in", values, "senderAddress");
            return (Criteria) this;
        }

        public Criteria andSenderAddressNotIn(List<String> values) {
            addCriterion("sender_address not in", values, "senderAddress");
            return (Criteria) this;
        }

        public Criteria andSenderAddressBetween(String value1, String value2) {
            addCriterion("sender_address between", value1, value2, "senderAddress");
            return (Criteria) this;
        }

        public Criteria andSenderAddressNotBetween(String value1, String value2) {
            addCriterion("sender_address not between", value1, value2, "senderAddress");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeIsNull() {
            addCriterion("currency_code is null");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeIsNotNull() {
            addCriterion("currency_code is not null");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeEqualTo(String value) {
            addCriterion("currency_code =", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeNotEqualTo(String value) {
            addCriterion("currency_code <>", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeGreaterThan(String value) {
            addCriterion("currency_code >", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeGreaterThanOrEqualTo(String value) {
            addCriterion("currency_code >=", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeLessThan(String value) {
            addCriterion("currency_code <", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeLessThanOrEqualTo(String value) {
            addCriterion("currency_code <=", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeLike(String value) {
            addCriterion("currency_code like", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeNotLike(String value) {
            addCriterion("currency_code not like", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeIn(List<String> values) {
            addCriterion("currency_code in", values, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeNotIn(List<String> values) {
            addCriterion("currency_code not in", values, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeBetween(String value1, String value2) {
            addCriterion("currency_code between", value1, value2, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeNotBetween(String value1, String value2) {
            addCriterion("currency_code not between", value1, value2, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountIsNull() {
            addCriterion("remittance_amount is null");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountIsNotNull() {
            addCriterion("remittance_amount is not null");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountEqualTo(BigDecimal value) {
            addCriterion("remittance_amount =", value, "remittanceAmount");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountNotEqualTo(BigDecimal value) {
            addCriterion("remittance_amount <>", value, "remittanceAmount");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountGreaterThan(BigDecimal value) {
            addCriterion("remittance_amount >", value, "remittanceAmount");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("remittance_amount >=", value, "remittanceAmount");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountLessThan(BigDecimal value) {
            addCriterion("remittance_amount <", value, "remittanceAmount");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("remittance_amount <=", value, "remittanceAmount");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountIn(List<BigDecimal> values) {
            addCriterion("remittance_amount in", values, "remittanceAmount");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountNotIn(List<BigDecimal> values) {
            addCriterion("remittance_amount not in", values, "remittanceAmount");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("remittance_amount between", value1, value2, "remittanceAmount");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("remittance_amount not between", value1, value2, "remittanceAmount");
            return (Criteria) this;
        }

        public Criteria andFeeAmountIsNull() {
            addCriterion("fee_amount is null");
            return (Criteria) this;
        }

        public Criteria andFeeAmountIsNotNull() {
            addCriterion("fee_amount is not null");
            return (Criteria) this;
        }

        public Criteria andFeeAmountEqualTo(BigDecimal value) {
            addCriterion("fee_amount =", value, "feeAmount");
            return (Criteria) this;
        }

        public Criteria andFeeAmountNotEqualTo(BigDecimal value) {
            addCriterion("fee_amount <>", value, "feeAmount");
            return (Criteria) this;
        }

        public Criteria andFeeAmountGreaterThan(BigDecimal value) {
            addCriterion("fee_amount >", value, "feeAmount");
            return (Criteria) this;
        }

        public Criteria andFeeAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fee_amount >=", value, "feeAmount");
            return (Criteria) this;
        }

        public Criteria andFeeAmountLessThan(BigDecimal value) {
            addCriterion("fee_amount <", value, "feeAmount");
            return (Criteria) this;
        }

        public Criteria andFeeAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fee_amount <=", value, "feeAmount");
            return (Criteria) this;
        }

        public Criteria andFeeAmountIn(List<BigDecimal> values) {
            addCriterion("fee_amount in", values, "feeAmount");
            return (Criteria) this;
        }

        public Criteria andFeeAmountNotIn(List<BigDecimal> values) {
            addCriterion("fee_amount not in", values, "feeAmount");
            return (Criteria) this;
        }

        public Criteria andFeeAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fee_amount between", value1, value2, "feeAmount");
            return (Criteria) this;
        }

        public Criteria andFeeAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fee_amount not between", value1, value2, "feeAmount");
            return (Criteria) this;
        }

        public Criteria andRecipientNameIsNull() {
            addCriterion("recipient_name is null");
            return (Criteria) this;
        }

        public Criteria andRecipientNameIsNotNull() {
            addCriterion("recipient_name is not null");
            return (Criteria) this;
        }

        public Criteria andRecipientNameEqualTo(String value) {
            addCriterion("recipient_name =", value, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameNotEqualTo(String value) {
            addCriterion("recipient_name <>", value, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameGreaterThan(String value) {
            addCriterion("recipient_name >", value, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameGreaterThanOrEqualTo(String value) {
            addCriterion("recipient_name >=", value, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameLessThan(String value) {
            addCriterion("recipient_name <", value, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameLessThanOrEqualTo(String value) {
            addCriterion("recipient_name <=", value, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameLike(String value) {
            addCriterion("recipient_name like", value, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameNotLike(String value) {
            addCriterion("recipient_name not like", value, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameIn(List<String> values) {
            addCriterion("recipient_name in", values, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameNotIn(List<String> values) {
            addCriterion("recipient_name not in", values, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameBetween(String value1, String value2) {
            addCriterion("recipient_name between", value1, value2, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientNameNotBetween(String value1, String value2) {
            addCriterion("recipient_name not between", value1, value2, "recipientName");
            return (Criteria) this;
        }

        public Criteria andRecipientAccountIsNull() {
            addCriterion("recipient_account is null");
            return (Criteria) this;
        }

        public Criteria andRecipientAccountIsNotNull() {
            addCriterion("recipient_account is not null");
            return (Criteria) this;
        }

        public Criteria andRecipientAccountEqualTo(String value) {
            addCriterion("recipient_account =", value, "recipientAccount");
            return (Criteria) this;
        }

        public Criteria andRecipientAccountNotEqualTo(String value) {
            addCriterion("recipient_account <>", value, "recipientAccount");
            return (Criteria) this;
        }

        public Criteria andRecipientAccountGreaterThan(String value) {
            addCriterion("recipient_account >", value, "recipientAccount");
            return (Criteria) this;
        }

        public Criteria andRecipientAccountGreaterThanOrEqualTo(String value) {
            addCriterion("recipient_account >=", value, "recipientAccount");
            return (Criteria) this;
        }

        public Criteria andRecipientAccountLessThan(String value) {
            addCriterion("recipient_account <", value, "recipientAccount");
            return (Criteria) this;
        }

        public Criteria andRecipientAccountLessThanOrEqualTo(String value) {
            addCriterion("recipient_account <=", value, "recipientAccount");
            return (Criteria) this;
        }

        public Criteria andRecipientAccountLike(String value) {
            addCriterion("recipient_account like", value, "recipientAccount");
            return (Criteria) this;
        }

        public Criteria andRecipientAccountNotLike(String value) {
            addCriterion("recipient_account not like", value, "recipientAccount");
            return (Criteria) this;
        }

        public Criteria andRecipientAccountIn(List<String> values) {
            addCriterion("recipient_account in", values, "recipientAccount");
            return (Criteria) this;
        }

        public Criteria andRecipientAccountNotIn(List<String> values) {
            addCriterion("recipient_account not in", values, "recipientAccount");
            return (Criteria) this;
        }

        public Criteria andRecipientAccountBetween(String value1, String value2) {
            addCriterion("recipient_account between", value1, value2, "recipientAccount");
            return (Criteria) this;
        }

        public Criteria andRecipientAccountNotBetween(String value1, String value2) {
            addCriterion("recipient_account not between", value1, value2, "recipientAccount");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneIsNull() {
            addCriterion("recipient_phone is null");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneIsNotNull() {
            addCriterion("recipient_phone is not null");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneEqualTo(String value) {
            addCriterion("recipient_phone =", value, "recipientPhone");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneNotEqualTo(String value) {
            addCriterion("recipient_phone <>", value, "recipientPhone");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneGreaterThan(String value) {
            addCriterion("recipient_phone >", value, "recipientPhone");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("recipient_phone >=", value, "recipientPhone");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneLessThan(String value) {
            addCriterion("recipient_phone <", value, "recipientPhone");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneLessThanOrEqualTo(String value) {
            addCriterion("recipient_phone <=", value, "recipientPhone");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneLike(String value) {
            addCriterion("recipient_phone like", value, "recipientPhone");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneNotLike(String value) {
            addCriterion("recipient_phone not like", value, "recipientPhone");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneIn(List<String> values) {
            addCriterion("recipient_phone in", values, "recipientPhone");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneNotIn(List<String> values) {
            addCriterion("recipient_phone not in", values, "recipientPhone");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneBetween(String value1, String value2) {
            addCriterion("recipient_phone between", value1, value2, "recipientPhone");
            return (Criteria) this;
        }

        public Criteria andRecipientPhoneNotBetween(String value1, String value2) {
            addCriterion("recipient_phone not between", value1, value2, "recipientPhone");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressIsNull() {
            addCriterion("recipient_address is null");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressIsNotNull() {
            addCriterion("recipient_address is not null");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressEqualTo(String value) {
            addCriterion("recipient_address =", value, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressNotEqualTo(String value) {
            addCriterion("recipient_address <>", value, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressGreaterThan(String value) {
            addCriterion("recipient_address >", value, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressGreaterThanOrEqualTo(String value) {
            addCriterion("recipient_address >=", value, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressLessThan(String value) {
            addCriterion("recipient_address <", value, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressLessThanOrEqualTo(String value) {
            addCriterion("recipient_address <=", value, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressLike(String value) {
            addCriterion("recipient_address like", value, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressNotLike(String value) {
            addCriterion("recipient_address not like", value, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressIn(List<String> values) {
            addCriterion("recipient_address in", values, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressNotIn(List<String> values) {
            addCriterion("recipient_address not in", values, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressBetween(String value1, String value2) {
            addCriterion("recipient_address between", value1, value2, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andRecipientAddressNotBetween(String value1, String value2) {
            addCriterion("recipient_address not between", value1, value2, "recipientAddress");
            return (Criteria) this;
        }

        public Criteria andInterbankStatusCodeIsNull() {
            addCriterion("interbank_status_code is null");
            return (Criteria) this;
        }

        public Criteria andInterbankStatusCodeIsNotNull() {
            addCriterion("interbank_status_code is not null");
            return (Criteria) this;
        }

        public Criteria andInterbankStatusCodeEqualTo(String value) {
            addCriterion("interbank_status_code =", value, "interbankStatusCode");
            return (Criteria) this;
        }

        public Criteria andInterbankStatusCodeNotEqualTo(String value) {
            addCriterion("interbank_status_code <>", value, "interbankStatusCode");
            return (Criteria) this;
        }

        public Criteria andInterbankStatusCodeGreaterThan(String value) {
            addCriterion("interbank_status_code >", value, "interbankStatusCode");
            return (Criteria) this;
        }

        public Criteria andInterbankStatusCodeGreaterThanOrEqualTo(String value) {
            addCriterion("interbank_status_code >=", value, "interbankStatusCode");
            return (Criteria) this;
        }

        public Criteria andInterbankStatusCodeLessThan(String value) {
            addCriterion("interbank_status_code <", value, "interbankStatusCode");
            return (Criteria) this;
        }

        public Criteria andInterbankStatusCodeLessThanOrEqualTo(String value) {
            addCriterion("interbank_status_code <=", value, "interbankStatusCode");
            return (Criteria) this;
        }

        public Criteria andInterbankStatusCodeLike(String value) {
            addCriterion("interbank_status_code like", value, "interbankStatusCode");
            return (Criteria) this;
        }

        public Criteria andInterbankStatusCodeNotLike(String value) {
            addCriterion("interbank_status_code not like", value, "interbankStatusCode");
            return (Criteria) this;
        }

        public Criteria andInterbankStatusCodeIn(List<String> values) {
            addCriterion("interbank_status_code in", values, "interbankStatusCode");
            return (Criteria) this;
        }

        public Criteria andInterbankStatusCodeNotIn(List<String> values) {
            addCriterion("interbank_status_code not in", values, "interbankStatusCode");
            return (Criteria) this;
        }

        public Criteria andInterbankStatusCodeBetween(String value1, String value2) {
            addCriterion("interbank_status_code between", value1, value2, "interbankStatusCode");
            return (Criteria) this;
        }

        public Criteria andInterbankStatusCodeNotBetween(String value1, String value2) {
            addCriterion("interbank_status_code not between", value1, value2, "interbankStatusCode");
            return (Criteria) this;
        }

        public Criteria andRemittanceNoteIsNull() {
            addCriterion("remittance_note is null");
            return (Criteria) this;
        }

        public Criteria andRemittanceNoteIsNotNull() {
            addCriterion("remittance_note is not null");
            return (Criteria) this;
        }

        public Criteria andRemittanceNoteEqualTo(String value) {
            addCriterion("remittance_note =", value, "remittanceNote");
            return (Criteria) this;
        }

        public Criteria andRemittanceNoteNotEqualTo(String value) {
            addCriterion("remittance_note <>", value, "remittanceNote");
            return (Criteria) this;
        }

        public Criteria andRemittanceNoteGreaterThan(String value) {
            addCriterion("remittance_note >", value, "remittanceNote");
            return (Criteria) this;
        }

        public Criteria andRemittanceNoteGreaterThanOrEqualTo(String value) {
            addCriterion("remittance_note >=", value, "remittanceNote");
            return (Criteria) this;
        }

        public Criteria andRemittanceNoteLessThan(String value) {
            addCriterion("remittance_note <", value, "remittanceNote");
            return (Criteria) this;
        }

        public Criteria andRemittanceNoteLessThanOrEqualTo(String value) {
            addCriterion("remittance_note <=", value, "remittanceNote");
            return (Criteria) this;
        }

        public Criteria andRemittanceNoteLike(String value) {
            addCriterion("remittance_note like", value, "remittanceNote");
            return (Criteria) this;
        }

        public Criteria andRemittanceNoteNotLike(String value) {
            addCriterion("remittance_note not like", value, "remittanceNote");
            return (Criteria) this;
        }

        public Criteria andRemittanceNoteIn(List<String> values) {
            addCriterion("remittance_note in", values, "remittanceNote");
            return (Criteria) this;
        }

        public Criteria andRemittanceNoteNotIn(List<String> values) {
            addCriterion("remittance_note not in", values, "remittanceNote");
            return (Criteria) this;
        }

        public Criteria andRemittanceNoteBetween(String value1, String value2) {
            addCriterion("remittance_note between", value1, value2, "remittanceNote");
            return (Criteria) this;
        }

        public Criteria andRemittanceNoteNotBetween(String value1, String value2) {
            addCriterion("remittance_note not between", value1, value2, "remittanceNote");
            return (Criteria) this;
        }

        public Criteria andZoneValIsNull() {
            addCriterion("zone_val is null");
            return (Criteria) this;
        }

        public Criteria andZoneValIsNotNull() {
            addCriterion("zone_val is not null");
            return (Criteria) this;
        }

        public Criteria andZoneValEqualTo(String value) {
            addCriterion("zone_val =", value, "zoneVal");
            return (Criteria) this;
        }

        public Criteria andZoneValNotEqualTo(String value) {
            addCriterion("zone_val <>", value, "zoneVal");
            return (Criteria) this;
        }

        public Criteria andZoneValGreaterThan(String value) {
            addCriterion("zone_val >", value, "zoneVal");
            return (Criteria) this;
        }

        public Criteria andZoneValGreaterThanOrEqualTo(String value) {
            addCriterion("zone_val >=", value, "zoneVal");
            return (Criteria) this;
        }

        public Criteria andZoneValLessThan(String value) {
            addCriterion("zone_val <", value, "zoneVal");
            return (Criteria) this;
        }

        public Criteria andZoneValLessThanOrEqualTo(String value) {
            addCriterion("zone_val <=", value, "zoneVal");
            return (Criteria) this;
        }

        public Criteria andZoneValLike(String value) {
            addCriterion("zone_val like", value, "zoneVal");
            return (Criteria) this;
        }

        public Criteria andZoneValNotLike(String value) {
            addCriterion("zone_val not like", value, "zoneVal");
            return (Criteria) this;
        }

        public Criteria andZoneValIn(List<String> values) {
            addCriterion("zone_val in", values, "zoneVal");
            return (Criteria) this;
        }

        public Criteria andZoneValNotIn(List<String> values) {
            addCriterion("zone_val not in", values, "zoneVal");
            return (Criteria) this;
        }

        public Criteria andZoneValBetween(String value1, String value2) {
            addCriterion("zone_val between", value1, value2, "zoneVal");
            return (Criteria) this;
        }

        public Criteria andZoneValNotBetween(String value1, String value2) {
            addCriterion("zone_val not between", value1, value2, "zoneVal");
            return (Criteria) this;
        }

        public Criteria andOptimisticLockVersionIsNull() {
            addCriterion("optimistic_lock_version is null");
            return (Criteria) this;
        }

        public Criteria andOptimisticLockVersionIsNotNull() {
            addCriterion("optimistic_lock_version is not null");
            return (Criteria) this;
        }

        public Criteria andOptimisticLockVersionEqualTo(Integer value) {
            addCriterion("optimistic_lock_version =", value, "optimisticLockVersion");
            return (Criteria) this;
        }

        public Criteria andOptimisticLockVersionNotEqualTo(Integer value) {
            addCriterion("optimistic_lock_version <>", value, "optimisticLockVersion");
            return (Criteria) this;
        }

        public Criteria andOptimisticLockVersionGreaterThan(Integer value) {
            addCriterion("optimistic_lock_version >", value, "optimisticLockVersion");
            return (Criteria) this;
        }

        public Criteria andOptimisticLockVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("optimistic_lock_version >=", value, "optimisticLockVersion");
            return (Criteria) this;
        }

        public Criteria andOptimisticLockVersionLessThan(Integer value) {
            addCriterion("optimistic_lock_version <", value, "optimisticLockVersion");
            return (Criteria) this;
        }

        public Criteria andOptimisticLockVersionLessThanOrEqualTo(Integer value) {
            addCriterion("optimistic_lock_version <=", value, "optimisticLockVersion");
            return (Criteria) this;
        }

        public Criteria andOptimisticLockVersionIn(List<Integer> values) {
            addCriterion("optimistic_lock_version in", values, "optimisticLockVersion");
            return (Criteria) this;
        }

        public Criteria andOptimisticLockVersionNotIn(List<Integer> values) {
            addCriterion("optimistic_lock_version not in", values, "optimisticLockVersion");
            return (Criteria) this;
        }

        public Criteria andOptimisticLockVersionBetween(Integer value1, Integer value2) {
            addCriterion("optimistic_lock_version between", value1, value2, "optimisticLockVersion");
            return (Criteria) this;
        }

        public Criteria andOptimisticLockVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("optimistic_lock_version not between", value1, value2, "optimisticLockVersion");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_rmrgt_reg_out
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_rmrgt_reg_out
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}