package org.example.common.domain.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.common.domain.dao.po.CustomerInfoPo;

public interface CustomerInfoPoMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String customerNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_info
     *
     * @mbg.generated
     */
    int insert(CustomerInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_info
     *
     * @mbg.generated
     */
    int insertSelective(CustomerInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_info
     *
     * @mbg.generated
     */
    CustomerInfoPo selectByPrimaryKey(String customerNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CustomerInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CustomerInfoPo record);
}