package org.example.common.domain.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.common.domain.dao.mdo.CustomerInfoMdo;

public interface CustomerInfoMdoMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String customerNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_info
     *
     * @mbg.generated
     */
    int insert(CustomerInfoMdo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_info
     *
     * @mbg.generated
     */
    int insertSelective(CustomerInfoMdo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_info
     *
     * @mbg.generated
     */

    CustomerInfoMdo selectByPrimaryKey(String customerNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CustomerInfoMdo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CustomerInfoMdo record);
}