package org.example.rmrgt.dao.mdo;

import java.util.Date;

public class RmrgtLifecycleMdo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_lifecycle.remittance_id
     *
     * @mbg.generated
     */
    private String remittanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_lifecycle.transaction_date
     *
     * @mbg.generated
     */
    private String transactionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_lifecycle.status_change_date
     *
     * @mbg.generated
     */
    private String statusChangeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_lifecycle.direction_code
     *
     * @mbg.generated
     */
    private String directionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_lifecycle.status_change_reason
     *
     * @mbg.generated
     */
    private String statusChangeReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_lifecycle.currency_code
     *
     * @mbg.generated
     */
    private String currencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_lifecycle.global_tracking_number
     *
     * @mbg.generated
     */
    private String globalTrackingNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_lifecycle.zone_val
     *
     * @mbg.generated
     */
    private String zoneVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_lifecycle.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rmrgt_lifecycle.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_lifecycle.remittance_id
     *
     * @return the value of tb_rmrgt_lifecycle.remittance_id
     *
     * @mbg.generated
     */
    public String getRemittanceId() {
        return remittanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_lifecycle.remittance_id
     *
     * @param remittanceId the value for tb_rmrgt_lifecycle.remittance_id
     *
     * @mbg.generated
     */
    public void setRemittanceId(String remittanceId) {
        this.remittanceId = remittanceId == null ? null : remittanceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_lifecycle.transaction_date
     *
     * @return the value of tb_rmrgt_lifecycle.transaction_date
     *
     * @mbg.generated
     */
    public String getTransactionDate() {
        return transactionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_lifecycle.transaction_date
     *
     * @param transactionDate the value for tb_rmrgt_lifecycle.transaction_date
     *
     * @mbg.generated
     */
    public void setTransactionDate(String transactionDate) {
        this.transactionDate = transactionDate == null ? null : transactionDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_lifecycle.status_change_date
     *
     * @return the value of tb_rmrgt_lifecycle.status_change_date
     *
     * @mbg.generated
     */
    public String getStatusChangeDate() {
        return statusChangeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_lifecycle.status_change_date
     *
     * @param statusChangeDate the value for tb_rmrgt_lifecycle.status_change_date
     *
     * @mbg.generated
     */
    public void setStatusChangeDate(String statusChangeDate) {
        this.statusChangeDate = statusChangeDate == null ? null : statusChangeDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_lifecycle.direction_code
     *
     * @return the value of tb_rmrgt_lifecycle.direction_code
     *
     * @mbg.generated
     */
    public String getDirectionCode() {
        return directionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_lifecycle.direction_code
     *
     * @param directionCode the value for tb_rmrgt_lifecycle.direction_code
     *
     * @mbg.generated
     */
    public void setDirectionCode(String directionCode) {
        this.directionCode = directionCode == null ? null : directionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_lifecycle.status_change_reason
     *
     * @return the value of tb_rmrgt_lifecycle.status_change_reason
     *
     * @mbg.generated
     */
    public String getStatusChangeReason() {
        return statusChangeReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_lifecycle.status_change_reason
     *
     * @param statusChangeReason the value for tb_rmrgt_lifecycle.status_change_reason
     *
     * @mbg.generated
     */
    public void setStatusChangeReason(String statusChangeReason) {
        this.statusChangeReason = statusChangeReason == null ? null : statusChangeReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_lifecycle.currency_code
     *
     * @return the value of tb_rmrgt_lifecycle.currency_code
     *
     * @mbg.generated
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_lifecycle.currency_code
     *
     * @param currencyCode the value for tb_rmrgt_lifecycle.currency_code
     *
     * @mbg.generated
     */
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode == null ? null : currencyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_lifecycle.global_tracking_number
     *
     * @return the value of tb_rmrgt_lifecycle.global_tracking_number
     *
     * @mbg.generated
     */
    public String getGlobalTrackingNumber() {
        return globalTrackingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_lifecycle.global_tracking_number
     *
     * @param globalTrackingNumber the value for tb_rmrgt_lifecycle.global_tracking_number
     *
     * @mbg.generated
     */
    public void setGlobalTrackingNumber(String globalTrackingNumber) {
        this.globalTrackingNumber = globalTrackingNumber == null ? null : globalTrackingNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_lifecycle.zone_val
     *
     * @return the value of tb_rmrgt_lifecycle.zone_val
     *
     * @mbg.generated
     */
    public String getZoneVal() {
        return zoneVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_lifecycle.zone_val
     *
     * @param zoneVal the value for tb_rmrgt_lifecycle.zone_val
     *
     * @mbg.generated
     */
    public void setZoneVal(String zoneVal) {
        this.zoneVal = zoneVal == null ? null : zoneVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_lifecycle.created_at
     *
     * @return the value of tb_rmrgt_lifecycle.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_lifecycle.created_at
     *
     * @param createdAt the value for tb_rmrgt_lifecycle.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rmrgt_lifecycle.updated_at
     *
     * @return the value of tb_rmrgt_lifecycle.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rmrgt_lifecycle.updated_at
     *
     * @param updatedAt the value for tb_rmrgt_lifecycle.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}