package org.example.rmrgt.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.example.rmrgt.dao.mdo.CustomerAccountInfoMdo;

@Mapper
public interface CustomerAccountInfoMdoMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_account_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String accountNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_account_info
     *
     * @mbg.generated
     */
    int insert(CustomerAccountInfoMdo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_account_info
     *
     * @mbg.generated
     */
    int insertSelective(CustomerAccountInfoMdo record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_account_info
     *
     * @mbg.generated
     */
    CustomerAccountInfoMdo selectByPrimaryKey(String accountNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_account_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CustomerAccountInfoMdo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer_account_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CustomerAccountInfoMdo record);
}