package org.example.rmrgt.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.example.rmrgt.dao.mdo.RmrgtLifecycleMdo;

@Mapper
public interface RmrgtLifecycleMdoMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String remittanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    int insert(RmrgtLifecycleMdo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    int insertSelective(RmrgtLifecycleMdo record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    RmrgtLifecycleMdo selectByPrimaryKey(String remittanceId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RmrgtLifecycleMdo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RmrgtLifecycleMdo record);
}