package org.example.rmrgt.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.example.rmrgt.dao.po.RmrgtRegInPo;

@Mapper
public interface RmrgtRegInPoMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_in
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String remittanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_in
     *
     * @mbg.generated
     */
    int insert(RmrgtRegInPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_in
     *
     * @mbg.generated
     */
    int insertSelective(RmrgtRegInPo record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_in
     *
     * @mbg.generated
     */
    RmrgtRegInPo selectByPrimaryKey(String remittanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_in
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RmrgtRegInPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_reg_in
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RmrgtRegInPo record);
}