package org.example.rmrgt.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.example.rmrgt.dao.po.RmrgtLifecyclePo;

@Mapper
public interface RmrgtLifecyclePoMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String remittanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    int insert(RmrgtLifecyclePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    int insertSelective(RmrgtLifecyclePo record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    RmrgtLifecyclePo selectByPrimaryKey(String remittanceId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RmrgtLifecyclePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rmrgt_lifecycle
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RmrgtLifecyclePo record);
}